name: Deploy sql2mermaid webpage
on:
  push:
    branches:
      - main
permissions:
  contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup Mermaid
        run: npm install mermaid

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install python deps 
        run: |
          python -m pip install build

      - name: Build wheel pyscript
        run: |
          python -m build --wheel --outdir pyscript/

      - name: Download polars
        run: wget -P pyscript https://github.com/pola-rs/polars/releases/download/py-1.19.0/polars-1.19.0-cp39-abi3-emscripten_3_1_58_wasm32.whl


      - name: Check files 
        run: |
          ls pyscript/

      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v4 
        with:
          folder: pyscript
          token: ${{ secrets.GITHUB_TOKEN }} 
